import type { Metadata } from "next";
import { getSession } from "@/lib/sessions";
import Providers from "@/components/Providers";

type Props = {
  children: React.ReactNode;
};

const description = "Mesa de regalos";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Props) {
  const session = await getSession();

  return (
    <html lang="es">
      <link rel="shortcut icon" href="/favicon.ico" />
      <meta name="description" content={description} />
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <body>
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  );
}
